# Generated by Django 6.0 on 2025-12-12 18:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., MTN Mobile Money, Orange Money",
                        max_length=50,
                        unique=True,
                        verbose_name="network name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code like MTN, OM, EU",
                        max_length=10,
                        unique=True,
                        verbose_name="network code",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color for UI display, e.g., #ffcc00 for MTN",
                        max_length=7,
                        verbose_name="brand color",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this network currently supported?",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "network",
                "verbose_name_plural": "networks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary login identifier",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Display name (how the user wants to be called)",
                        max_length=50,
                        verbose_name="username",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Full legal name for records",
                        max_length=150,
                        verbose_name="full name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="With country code, e.g., +237677123456",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 9-15 digits, optionally starting with +",
                                regex="^\\+?[0-9]{9,15}$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has the user verified their email address?",
                        verbose_name="email verified",
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True,
                        help_text="Google account identifier for OAuth",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Google ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True,
                        help_text="URL to profile picture (from Google or uploaded)",
                        max_length=500,
                        verbose_name="profile picture URL",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Can access admin site",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Account is active and can log in",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Unique name like "Akwa Shop" or "Molyko Kiosk"',
                        max_length=100,
                        verbose_name="kiosk name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-generated unique identifier",
                        max_length=120,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or address description",
                        max_length=255,
                        verbose_name="location description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this kiosk currently operational?",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created and owns this kiosk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_kiosks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kiosk",
                "verbose_name_plural": "kiosks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KioskMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("AGENT", "Agent")],
                        default="AGENT",
                        help_text="Admin has full access, Agent has limited access",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="The kiosk this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.kiosk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is a member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiosk_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kiosk member",
                "verbose_name_plural": "kiosk members",
                "ordering": ["-joined_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kiosk", "user"), name="unique_kiosk_member"
                    )
                ],
                "unique_together": {("kiosk", "user")},
            },
        ),
        migrations.CreateModel(
            name="CommissionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum transaction amount for this rate (inclusive)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="minimum amount",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum transaction amount for this rate (inclusive)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="maximum amount",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage"),
                        ],
                        default="FIXED",
                        help_text="Is the commission a fixed amount or percentage?",
                        max_length=15,
                        verbose_name="rate type",
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fixed amount in CFA or percentage (e.g., 0.3 for 0.3%)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="rate value",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this rate currently in effect?",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "network",
                    models.ForeignKey(
                        help_text="Which network this rate applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rates",
                        to="core.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "commission rate",
                "verbose_name_plural": "commission rates",
                "ordering": ["network", "min_amount"],
                "indexes": [
                    models.Index(
                        fields=["network", "is_active"],
                        name="core_commis_network_7d3a09_idx",
                    ),
                    models.Index(
                        fields=["min_amount", "max_amount"],
                        name="core_commis_min_amo_ce023b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short notification title",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Detailed notification content",
                        verbose_name="message",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INVITE", "Kiosk Invitation"),
                            ("ALERT", "Alert"),
                            ("FRAUD", "Fraud Warning"),
                            ("SYSTEM", "System Message"),
                            ("SUMMARY", "Daily Summary"),
                        ],
                        default="SYSTEM",
                        help_text="Category of notification",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Has the user seen this notification?",
                        verbose_name="read",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate to when clicked (e.g., invitation acceptance)",
                        max_length=500,
                        verbose_name="action URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was marked as read",
                        null=True,
                        verbose_name="read at",
                    ),
                ),
                (
                    "related_kiosk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related kiosk if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.kiosk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this notification is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="core_notifi_user_id_f286cd_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="core_notifi_notific_cbfe88_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit (Cash In)"),
                            ("WITHDRAWAL", "Withdrawal (Cash Out)"),
                        ],
                        help_text="Deposit = customer sending money, Withdrawal = customer taking cash",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount in CFA",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "calculated_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Auto-calculated commission based on rate rules",
                        max_digits=10,
                        verbose_name="calculated profit",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Final profit (can be edited by user)",
                        max_digits=10,
                        verbose_name="actual profit",
                    ),
                ),
                (
                    "profit_was_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Was the profit manually overridden?",
                        verbose_name="profit was edited",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Customer phone number if known",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 9-15 digits, optionally starting with +",
                                regex="^\\+?[0-9]{9,15}$",
                            )
                        ],
                        verbose_name="customer phone",
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from the receipt",
                        max_length=100,
                        verbose_name="transaction reference",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes about this transaction",
                        verbose_name="notes",
                    ),
                ),
                (
                    "receipt_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of the transaction receipt",
                        null=True,
                        upload_to="receipts/%Y/%m/%d/",
                        verbose_name="receipt photo",
                    ),
                ),
                (
                    "sms_text",
                    models.TextField(
                        blank=True,
                        help_text="Full text message from the receipt if shared",
                        verbose_name="SMS text",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the transaction occurred",
                        verbose_name="transaction time",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Which kiosk this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.kiosk",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        help_text="Which mobile network was used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.network",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="The agent who recorded this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "-timestamp"],
                        name="core_transa_kiosk_i_af6cd7_idx",
                    ),
                    models.Index(
                        fields=["recorded_by", "-timestamp"],
                        name="core_transa_recorde_dbc404_idx",
                    ),
                    models.Index(
                        fields=["network", "transaction_type"],
                        name="core_transa_network_07af21_idx",
                    ),
                    models.Index(
                        fields=["customer_phone"], name="core_transa_custome_842bef_idx"
                    ),
                    models.Index(
                        fields=["transaction_ref"],
                        name="core_transa_transac_22fca0_idx",
                    ),
                ],
            },
        ),
    ]
