# Generated by Django 6.0 on 2025-12-13 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Was email notification sent?",
                verbose_name="email sent",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High")],
                default="NORMAL",
                help_text="Notification priority level",
                max_length=10,
                verbose_name="priority",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="push_sent",
            field=models.BooleanField(
                default=False,
                help_text="Was push notification sent?",
                verbose_name="push sent",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Related transaction if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INVITE", "Kiosk Invitation"),
                    ("ALERT", "Alert"),
                    ("FRAUD", "Fraud Warning"),
                    ("SYSTEM", "System Message"),
                    ("SUMMARY", "Daily Summary"),
                    ("TRANSACTION", "Transaction Alert"),
                ],
                default="SYSTEM",
                help_text="Category of notification",
                max_length=15,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive browser push notifications",
                        verbose_name="push notifications enabled",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications",
                        verbose_name="email notifications enabled",
                    ),
                ),
                (
                    "invites_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive kiosk invitation notifications",
                        verbose_name="invitation notifications",
                    ),
                ),
                (
                    "fraud_alerts_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive fraud warning notifications",
                        verbose_name="fraud alert notifications",
                    ),
                ),
                (
                    "system_messages_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive system updates and announcements",
                        verbose_name="system message notifications",
                    ),
                ),
                (
                    "transaction_alerts_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications when team members make transactions",
                        verbose_name="transaction notifications",
                    ),
                ),
                (
                    "daily_summary_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive daily summary at specified time",
                        verbose_name="daily summary",
                    ),
                ),
                (
                    "summary_time",
                    models.TimeField(
                        default="20:00",
                        help_text="Time to receive daily summary (local time)",
                        verbose_name="summary delivery time",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(
                        help_text="Push service endpoint URL",
                        verbose_name="endpoint URL",
                    ),
                ),
                (
                    "p256dh_key",
                    models.TextField(
                        blank=True,
                        help_text="Client public key for encryption",
                        verbose_name="p256dh key",
                    ),
                ),
                (
                    "auth_key",
                    models.TextField(
                        blank=True,
                        help_text="Authentication secret",
                        verbose_name="auth key",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device user agent",
                        max_length=500,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this subscription still valid?",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a push was sent to this subscription",
                        null=True,
                        verbose_name="last used at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "push subscription",
                "verbose_name_plural": "push subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="core_pushsu_user_id_35c075_idx",
                    )
                ],
            },
        ),
    ]
