# Generated by Django 6.0 on 2025-12-13 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_notification_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number of the suspected scammer",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 9-15 digits, optionally starting with +",
                                regex="^\\+?[0-9]{9,15}$",
                            )
                        ],
                        verbose_name="scammer phone",
                    ),
                ),
                (
                    "scammer_name",
                    models.CharField(
                        blank=True,
                        help_text="Name used by the scammer (if known)",
                        max_length=100,
                        verbose_name="scammer name",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("FAKE_SMS", "Fake SMS"),
                            ("SCAM_CALL", "Scam Call"),
                            ("FAKE_CALLER", "Fake Caller"),
                            ("DANGEROUS", "Dangerous Warning"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=15,
                        verbose_name="type of fraud",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What happened? Describe the incident",
                        verbose_name="description",
                    ),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot of fake SMS or other proof",
                        null=True,
                        upload_to="fraud_proofs/%Y/%m/",
                        verbose_name="proof screenshot",
                    ),
                ),
                (
                    "reporter_location",
                    models.CharField(
                        blank=True,
                        help_text="Location for proximity alerts",
                        max_length=200,
                        verbose_name="location",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="reported at"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True if 3+ independent reports",
                        verbose_name="verified threat",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who submitted this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter_kiosk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kiosk where the incident occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reports",
                        to="core.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "fraud report",
                "verbose_name_plural": "fraud reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KioskInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the person being invited",
                        max_length=254,
                        verbose_name="invitee email",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("AGENT", "Agent")],
                        default="AGENT",
                        help_text="Role the invitee will have upon acceptance",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for invitation link",
                        unique=True,
                        verbose_name="invitation token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from inviter",
                        verbose_name="personal message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Invitation expiration date",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="accepted at"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="The user who sent the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="The kiosk the user is being invited to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "kiosk invitation",
                "verbose_name_plural": "kiosk invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
