# Generated by Django 6.0 on 2025-12-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Customer/sender name if known",
                max_length=100,
                verbose_name="customer name",
            ),
        ),
    ]
