# Generated by Django 6.0 on 2025-12-14 01:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_customer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The date for this opening balance",
                        verbose_name="date",
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Cash in drawer at start of day",
                        max_digits=12,
                        verbose_name="opening cash",
                    ),
                ),
                (
                    "adjustment_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No adjustment"),
                            ("CASH_INJECTION", "Cash Injection"),
                            ("DISCREPANCY", "Discrepancy Correction"),
                            ("FLOAT_RECHARGE", "Float Recharge"),
                            ("OTHER", "Other"),
                        ],
                        default="",
                        help_text="Why the opening balance differs from yesterday's closing",
                        max_length=20,
                        verbose_name="adjustment reason",
                    ),
                ),
                (
                    "adjustment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the adjustment",
                        verbose_name="adjustment notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who set this opening balance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Which kiosk this opening balance belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_balances",
                        to="core.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily opening balance",
                "verbose_name_plural": "daily opening balances",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NetworkFloatBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_float",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Float balance for this network at start of day",
                        max_digits=12,
                        verbose_name="opening float",
                    ),
                ),
                (
                    "daily_balance",
                    models.ForeignKey(
                        help_text="The daily balance this belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_floats",
                        to="core.dailyopeningbalance",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        help_text="Which network this float balance is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="float_balances",
                        to="core.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "network float balance",
                "verbose_name_plural": "network float balances",
            },
        ),
        migrations.AddIndex(
            model_name="dailyopeningbalance",
            index=models.Index(
                fields=["kiosk", "-date"], name="core_dailyo_kiosk_i_948e1b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyopeningbalance",
            unique_together={("kiosk", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="networkfloatbalance",
            unique_together={("daily_balance", "network")},
        ),
    ]
