# Generated by Django 6.0 on 2025-12-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_daily_opening_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit (Cash In)"),
                    ("WITHDRAWAL", "Withdrawal (Cash Out)"),
                    ("PROFIT_WITHDRAWAL", "Profit Withdrawal"),
                ],
                help_text="Deposit = customer sending money, Withdrawal = customer taking cash",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
