# Generated by Django 6.0 on 2025-12-14 12:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_increase_transaction_type_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCommissionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit (Cash In)"),
                            ("WITHDRAWAL", "Withdrawal (Cash Out)"),
                        ],
                        help_text="Does this rate apply to deposits or withdrawals?",
                        max_length=15,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum transaction amount for this rate (inclusive)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="minimum amount",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum transaction amount for this rate (inclusive)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="maximum amount",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage"),
                        ],
                        default="PERCENTAGE",
                        help_text="Is the commission a fixed amount or percentage?",
                        max_length=15,
                        verbose_name="rate type",
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="For deposits: % of amount or fixed. For withdrawals: % of network fee or fixed.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="rate value",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this rate currently in effect?",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Which kiosk/agent this rate applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_commission_rates",
                        to="core.kiosk",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        help_text="Which network this rate applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_commission_rates",
                        to="core.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent commission rate",
                "verbose_name_plural": "agent commission rates",
                "ordering": ["kiosk", "network", "transaction_type", "min_amount"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "network", "transaction_type", "is_active"],
                        name="core_agentc_kiosk_i_eef5f6_idx",
                    ),
                    models.Index(
                        fields=["min_amount", "max_amount"],
                        name="core_agentc_min_amo_a3b2b1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "kiosk",
                            "network",
                            "transaction_type",
                            "min_amount",
                            "max_amount",
                        ),
                        name="unique_agent_rate_range",
                    )
                ],
            },
        ),
    ]
