# Generated by Django 6.0 on 2025-12-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_agent_commission_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The date this report covers",
                        verbose_name="report date",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="All computed metrics stored as JSON",
                        verbose_name="report data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Which kiosk this report is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="core.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily report",
                "verbose_name_plural": "daily reports",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "-date"], name="core_dailyr_kiosk_i_7f331c_idx"
                    )
                ],
                "unique_together": {("kiosk", "date")},
            },
        ),
    ]
